import { Recipe } from '../schemas/index.js';

export const EXPANDED_RECIPES: Recipe[] = [
  // 1. 水产海鲜类
  {
    id: 'recipe-pan-seared-salmon',
    name: '香煎黑椒三文鱼',
    category: '海鲜水产',
    cuisine: '西餐轻食',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '三文鱼', amount: '200g', required: true },
      { name: '黑胡椒', amount: '适量', required: false },
      { name: '盐', amount: '1小勺', required: false },
      { name: '黄油', amount: '10g', required: false },
      { name: '柠檬', amount: '半个', required: false },
    ],
    instructions: [
      '三文鱼洗净用厨房纸彻底吸干表面水分，两面撒少许盐和现磨黑胡椒腌制5分钟。',
      '平底锅中火烧热，放入黄油或少许橄榄油融化。',
      '皮朝下放入三文鱼中火慢煎2-3分钟至金黄酥脆，翻面继续煎2分钟至八九分熟。',
      '出锅装盘，淋少许新鲜柠檬汁提鲜即可享用。',
    ],
    tips: '煎鱼前务必吸干水分，皮朝下慢煎能逼出鱼油使鱼皮格外香脆。',
    image_url: '/images/dishes/recipe_pan_seared_salmon.webp',
  },
  {
    id: 'recipe-salmon-salad',
    name: '三文鱼轻食温沙拉',
    category: '轻食沙拉',
    cuisine: '西餐轻食',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 5,
    servings: 1,
    ingredients: [
      { name: '三文鱼', amount: '150g', required: true },
      { name: '黄瓜', amount: '半根', required: false },
      { name: '鸡蛋', amount: '1个', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '黑胡椒', amount: '少许', required: false },
    ],
    instructions: [
      '鸡蛋煮熟切瓣，黄瓜洗净切薄片。',
      '三文鱼切小块，热锅少油两面煎至断生微焦。',
      '沙拉碗中铺入黄瓜片、熟鸡蛋，摆上煎香的三文鱼块。',
      '淋入少许生抽或低卡油醋汁，撒黑胡椒拌匀。',
    ],
    tips: '三文鱼富含Omega-3健康油脂，搭配水煮蛋是完美的减脂增肌餐。',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
  },
  {
    id: 'recipe-steamed-shrimp',
    name: '白灼基围虾',
    category: '海鲜水产',
    cuisine: '粤菜',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 5,
    servings: 2,
    ingredients: [
      { name: '虾', amount: '300g', required: true },
      { name: '生姜', amount: '3片', required: false },
      { name: '大葱', amount: '1根', required: false },
      { name: '生抽', amount: '2勺', required: false },
    ],
    instructions: [
      '鲜虾剪去虾须挑出虾线，清洗干净沥干。',
      '锅内加水，放入姜片和葱结大火烧沸。',
      '水大滚后倒入鲜虾，加1勺料酒，大火煮约2-3分钟至虾身弯曲变红即捞出。',
      '调蘸料：蒜末加生抽、少许香油调匀，剥壳蘸食。',
    ],
    tips: '水一定要彻底沸腾再下虾，煮至弯曲变红立刻捞出，肉质最紧实弹牙。',
    image_url: '/images/dishes/recipe_steamed_shrimp.webp',
  },
  {
    id: 'recipe-garlic-steamed-shrimp',
    name: '蒜蓉粉丝蒸大虾',
    category: '海鲜水产',
    cuisine: '粤菜',
    difficulty: '中等',
    prep_time: 15,
    cook_time: 8,
    servings: 3,
    ingredients: [
      { name: '虾', amount: '300g', required: true },
      { name: '大蒜', amount: '1头', required: true },
      { name: '粉丝', amount: '1把', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '大葱', amount: '1根', required: false },
    ],
    instructions: [
      '粉丝温水泡软铺在盘底；虾开背去虾线，整齐码在粉丝上。',
      '大蒜切末，一半下油锅小火炸至金黄，与生蒜末、生抽、少许糖拌匀成金银蒜蓉。',
      '将金银蒜蓉均匀铺在开背的虾肉上。',
      '蒸锅水开后大火蒸5-6分钟，出锅撒葱花，淋少许热油激发出香味。',
    ],
    tips: '金银蒜（熟蒜加生蒜）蒜香浓郁且不发苦，底部的粉丝吸饱虾汁特别入味。',
    image_url: '/images/dishes/recipe_garlic_steamed_shrimp.webp',
  },
  {
    id: 'recipe-shrimp-egg',
    name: '鲜虾仁滑蛋',
    category: '海鲜水产',
    cuisine: '粤菜',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 5,
    servings: 2,
    ingredients: [
      { name: '虾', amount: '150g', required: true },
      { name: '鸡蛋', amount: '3个', required: true },
      { name: '大葱', amount: '1根', required: false },
      { name: '盐', amount: '少许', required: false },
    ],
    instructions: [
      '虾仁加少许盐、淀粉抓匀上浆；鸡蛋加少许盐和水淀粉充分打散。',
      '热锅少油，下虾仁滑炒至变色八分熟盛出。',
      '将炒好的虾仁倒入蛋液中拌匀。',
      '锅内再倒油中火烧热，倒入混合蛋液，待底部稍凝固用锅铲从边缘向中间轻推，至蛋液九分熟立刻关火盛盘。',
    ],
    tips: '蛋液加少许水淀粉能锁住水分保持嫩滑，不要过分翻炒以保持大片滑蛋质感。',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500',
  },

  // 2. 水果、早餐与快手轻食类
  {
    id: 'recipe-banana-pancake',
    name: '香蕉燕麦低卡松饼',
    category: '轻食烘焙',
    cuisine: '快手早餐',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '香蕉', amount: '1根', required: true },
      { name: '鸡蛋', amount: '1个', required: true },
      { name: '燕麦', amount: '30g', required: false },
      { name: '牛奶', amount: '30ml', required: false },
    ],
    instructions: [
      '香蕉剥皮用叉子压成细腻的果泥。',
      '打入一个鸡蛋，加入即食燕麦片和牛奶充分搅拌均匀成稠糊状。',
      '不粘平底锅不用倒油或刷极微量油，微火预热。',
      '用勺子舀入面糊摊成小圆饼，慢煎至表面微凝固起小孔翻面，两面微黄熟透即可出锅。',
    ],
    tips: '完全不需要额外加糖，成熟香蕉自带天然香甜，低卡又有饱腹感。',
    image_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500',
  },
  {
    id: 'recipe-banana-toast',
    name: '焦糖香蕉烤吐司',
    category: '轻食烘焙',
    cuisine: '快手早餐',
    difficulty: '简单',
    prep_time: 3,
    cook_time: 5,
    servings: 1,
    ingredients: [
      { name: '香蕉', amount: '1根', required: true },
      { name: '面包', amount: '1片', required: true },
      { name: '黄油', amount: '5g', required: false },
      { name: '糖', amount: '半勺', required: false },
    ],
    instructions: [
      '吐司单面抹少许黄油，香蕉切薄圆片整齐铺满吐司表面。',
      '在香蕉片表面均匀筛或撒少许白糖。',
      '放入烤箱或空气炸锅180℃烤4-5分钟，至香蕉边缘微焦糖化出香气。',
      '取出趁热食用，外脆里糯。',
    ],
    tips: '熟透带芝麻点的香蕉烘烤后甜度更高，也可以在平底锅中小火焖煎。',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500',
  },
  {
    id: 'recipe-banana-yogurt-bowl',
    name: '香蕉坚果酸奶碗',
    category: '轻食沙拉',
    cuisine: '快手早餐',
    difficulty: '简单',
    prep_time: 3,
    cook_time: 0,
    servings: 1,
    ingredients: [
      { name: '香蕉', amount: '1根', required: true },
      { name: '酸奶', amount: '1盒(150g)', required: true },
      { name: '燕麦', amount: '20g', required: false },
    ],
    instructions: [
      '碗底倒入浓稠酸奶铺平。',
      '香蕉去皮切斜片，整齐码在酸奶上方。',
      '撒上即食燕麦或手头现有的坚果碎即可开吃。',
    ],
    tips: '无需开火，3分钟搞定营养均衡的高蛋白高纤维早餐。',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500',
  },

  // 3. 牛肉与健身高蛋白类
  {
    id: 'recipe-black-pepper-beef',
    name: '黑椒洋葱炒牛肉',
    category: '家常菜',
    cuisine: '中餐',
    difficulty: '中等',
    prep_time: 12,
    cook_time: 6,
    servings: 2,
    ingredients: [
      { name: '牛肉', amount: '200g', required: true },
      { name: '洋葱', amount: '半个', required: true },
      { name: '青椒', amount: '1个', required: false },
      { name: '黑胡椒', amount: '1勺', required: false },
      { name: '生抽', amount: '2勺', required: false },
    ],
    instructions: [
      '牛肉逆着纹理切薄片，加生抽、料酒、淀粉和少许食用油抓匀腌制10分钟。',
      '洋葱、青椒切块备用。',
      '热锅热油，下牛肉大火快炒至八分熟变色立刻盛出。',
      '底油爆炒洋葱和青椒断生出香味，倒回牛肉，撒入现磨黑胡椒碎和大火翻炒均匀出锅。',
    ],
    tips: '牛肉逆纹切断纤维才嫩，大火爆炒时间切忌过长，刚变色就出锅最鲜嫩。',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500',
  },
  {
    id: 'recipe-beef-tomato-soup',
    name: '番茄金针菇肥牛汤',
    category: '靓汤羹品',
    cuisine: '中餐',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 10,
    servings: 2,
    ingredients: [
      { name: '肥牛', amount: '150g', required: true },
      { name: '西红柿', amount: '2个', required: true },
      { name: '金针菇', amount: '1把', required: false },
      { name: '大蒜', amount: '2瓣', required: false },
      { name: '生抽', amount: '1勺', required: false },
    ],
    instructions: [
      '西红柿切小块，金针菇去根撕开洗净。',
      '沸水锅中下肥牛片焯水变色即捞出沥干。',
      '热锅少油爆香蒜末，下西红柿块翻炒按压出浓厚沙汁。',
      '倒入适量清水大火煮开，下入金针菇煮2分钟。',
      '下入焯好的肥牛片，加1勺生抽和少许盐，翻匀煮沸即关火出锅。',
    ],
    tips: '肥牛提前焯水去浮沫，番茄一定要炒透出红沙汤汁才会酸甜浓郁。',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=500',
  },
  {
    id: 'recipe-chicken-breast-salad',
    name: '香煎黑椒鸡胸肉',
    category: '家常菜',
    cuisine: '快手轻食',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: '250g', required: true },
      { name: '生抽', amount: '1勺', required: false },
      { name: '黑胡椒', amount: '1勺', required: false },
      { name: '生姜', amount: '2片', required: false },
    ],
    instructions: [
      '鸡胸肉从中间横切片成两半，表面划十字花刀便于入味。',
      '加生抽、料酒、生姜片、黑胡椒粉抓匀腌制10分钟。',
      '平底锅喷少许油中火烧热，放入鸡胸肉煎至一面定型微金黄。',
      '翻面继续小火慢煎，加盖焖煎2分钟确保内部熟透且保持汁水，出锅切条。',
    ],
    tips: '加盖小火焖煎是鸡胸肉多汁不柴的核心技巧。',
    image_url: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500',
  },

  // 4. 蔬菜、豆腐与经典快手家常
  {
    id: 'recipe-potato-shreds',
    name: '酸辣土豆丝',
    category: '家常菜',
    cuisine: '中餐',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 4,
    servings: 2,
    ingredients: [
      { name: '土豆', amount: '2个', required: true },
      { name: '辣椒', amount: '2个', required: false },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '香醋', amount: '2勺', required: false },
    ],
    instructions: [
      '土豆去皮切均匀细丝，放入清水中多淘洗两遍洗去多余淀粉。',
      '青红椒切丝，大蒜切片。',
      '热锅热油，下蒜片、干辣椒爆香。',
      '倒入沥干水分的土豆丝，大火急火快炒1-2分钟至断生透明。',
      '沿锅边淋入香醋，加适量盐翻炒均匀立刻出锅。',
    ],
    tips: '多淘洗去掉淀粉是大火爆炒爽脆的关键，香醋一定要出锅前沿锅边淋入出锅气。',
    image_url: '/images/dishes/recipe_potato_shreds.webp',
  },
  {
    id: 'recipe-tofu-egg',
    name: '家常肉末烧豆腐',
    category: '家常菜',
    cuisine: '中餐',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 10,
    servings: 3,
    ingredients: [
      { name: '豆腐', amount: '1块', required: true },
      { name: '猪肉', amount: '80g', required: false },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '大葱', amount: '1根', required: false },
      { name: '生抽', amount: '2勺', required: false },
    ],
    instructions: [
      '豆腐切方块，沸水中加盐焯水1分钟沥出定型。',
      '锅内少油爆香葱蒜末，下肉末煸炒散变色。',
      '倒入1碗清水和生抽、蚝油调味煮开，下入豆腐块中小火炖煮5分钟入味。',
      '淋入少许水淀粉勾芡，汤汁浓稠裹匀即可出锅。',
    ],
    tips: '豆腐焯盐水不仅去除豆腥味，还能让豆腐更紧实不易碎。',
    image_url: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=500',
  },
  {
    id: 'recipe-cabbage-stir-fry',
    name: '手撕手剥包菜',
    category: '家常菜',
    cuisine: '中餐',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 4,
    servings: 2,
    ingredients: [
      { name: '白菜', amount: '半个', required: true },
      { name: '大蒜', amount: '4瓣', required: false },
      { name: '辣椒', amount: '2个', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '香醋', amount: '1勺', required: false },
    ],
    instructions: [
      '包菜/大白菜洗净，用手撕成适口大片，沥干水分。',
      '热锅热油，下蒜片、辣椒段煸出香味。',
      '倒入包菜大火快速翻炒至变软塌陷。',
      '加入生抽、少许盐和香醋，继续大火快炒10秒出锅。',
    ],
    tips: '用手撕比刀切更容易附着调味汁，锅气越足越脆嫩。',
    image_url: '/images/dishes/recipe_cabbage_stir_fry.webp',
  },
  {
    id: 'recipe-egg-drop-soup',
    name: '西红柿紫菜蛋花汤',
    category: '靓汤羹品',
    cuisine: '中餐',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 5,
    servings: 2,
    ingredients: [
      { name: '鸡蛋', amount: '2个', required: true },
      { name: '西红柿', amount: '1个', required: true },
      { name: '大葱', amount: '1根', required: false },
      { name: '香油', amount: '少许', required: false },
    ],
    instructions: [
      '西红柿切薄丁，鸡蛋打散成细腻蛋液。',
      '热锅一点底油爆香葱花，下番茄丁炒出红汤。',
      '加入两碗清水大火烧沸，撒少许盐调味。',
      '关微火或关火，将蛋液顺着锅沿缓缓画圈淋入，待蛋花漂浮凝固轻轻搅散。',
      '出锅前滴两滴香油，撒上葱花。',
    ],
    tips: '淋蛋液时关微火或离火，蛋花会如云朵般轻盈舒展，绝不结硬块。',
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=500',
  },

  // ==========================================
  // 5. 茄子专题（高频蔬菜，蒜香/肉末/鱼香）
  // ==========================================
  {
    id: 'recipe-garlic-steamed-eggplant',
    name: '蒜香烤茄子',
    category: '家常菜',
    cuisine: '中餐',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 15,
    servings: 2,
    ingredients: [
      { name: '茄子', amount: '2根', required: true },
      { name: '大蒜', amount: '1头', required: true },
      { name: '小葱', amount: '2根', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '孜然粉', amount: '1小勺', required: false },
    ],
    instructions: [
      '茄子洗净开水上锅大火蒸8-10分钟至软透（或烤箱200度预先烤软），中间剖开划几道十字刀不划破外皮。',
      '大蒜切成细蓉，热锅温油下大半蒜末小火炒香炒至微黄，加入生抽、蚝油、孜然粉调成灵魂蒜蓉酱。',
      '将炒好的蒜蓉酱均匀平铺在茄子剖面上，撒上剩余生蒜末。',
      '放入烤箱200℃烤8分钟（或蒸锅继续大火蒸5分钟）至蒜香充分渗入茄肉，出锅撒小葱花即可。',
    ],
    tips: '先蒸至软糯再铺酱烤制，茄肉多汁软烂不发干，金银蒜蓉香味层次更丰富。',
    image_url: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?w=500',
  },
  {
    id: 'recipe-pork-eggplant',
    name: '肉末风味茄子',
    category: '家常菜',
    cuisine: '川湘家常',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 10,
    servings: 2,
    ingredients: [
      { name: '茄子', amount: '2根', required: true },
      { name: '猪肉', amount: '100g', required: true },
      { name: '大蒜', amount: '4瓣', required: false },
      { name: '生姜', amount: '2片', required: false },
      { name: '青椒', amount: '1根', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '豆瓣酱', amount: '1勺', required: false },
    ],
    instructions: [
      '茄子洗净切长条，撒少许盐抓匀腌制5分钟，挤掉渗出的黑水。',
      '猪肉剁成肉末，青椒切丁，生姜大蒜切末备用。',
      '热锅少油下肉末煸炒至散开变色出油，加入姜蒜末和豆瓣酱炒出诱人红油。',
      '倒入杀过水的茄子大火翻炒至变软入味，调入生抽和少许白糖。',
      '撒入青椒碎大火快速翻炒1分钟，汤汁收浓即可装盘。',
    ],
    tips: '茄子提前加盐杀水，下锅翻炒不仅不吸油，而且熟得更快、口感鲜香软糯。',
    image_url: '/images/dishes/recipe_pork_eggplant.webp',
  },
  {
    id: 'recipe-yuxiang-eggplant',
    name: '鱼香茄子煲',
    category: '家常菜',
    cuisine: '川菜',
    difficulty: '中等',
    prep_time: 10,
    cook_time: 12,
    servings: 3,
    ingredients: [
      { name: '茄子', amount: '2根', required: true },
      { name: '猪肉', amount: '80g', required: false },
      { name: '大蒜', amount: '5瓣', required: true },
      { name: '生姜', amount: '1小块', required: false },
      { name: '葱', amount: '1根', required: false },
      { name: '香醋', amount: '2勺', required: false },
      { name: '白糖', amount: '1.5勺', required: false },
      { name: '生抽', amount: '1.5勺', required: false },
      { name: '淀粉', amount: '1勺', required: false },
    ],
    instructions: [
      '茄子滚刀切块，撒少许干淀粉抓匀；小碗调鱼香汁（生抽、香醋、糖、淀粉加半碗清水拌匀）。',
      '锅中多放少许油，下入茄子中小火半煎半炸至表面微黄变软盛出沥油。',
      '底油爆香姜蒜末和猪肉末，淋入调好的鱼香汁大火煮沸至起大泡。',
      '倒回炸软的茄子快速颠锅翻炒裹匀酱汁。',
      '换入烧热的砂锅煲中，小火焖煨半分钟激发出香气，撒上葱花趁热上桌。',
    ],
    tips: '经典的鱼香黄金比例为醋:糖:生抽约4:3:3，咸甜微酸带蒜香，极其下饭。',
    image_url: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=500',
  },

  // ==========================================
  // 6. 猪肉与排骨类（硬菜靓汤、湘味小炒）
  // ==========================================
  {
    id: 'recipe-sweet-sour-ribs',
    name: '糖醋排骨',
    category: '家常菜',
    cuisine: '本帮江浙',
    difficulty: '中等',
    prep_time: 10,
    cook_time: 25,
    servings: 3,
    ingredients: [
      { name: '排骨', amount: '500g', required: true },
      { name: '生姜', amount: '4片', required: false },
      { name: '大葱', amount: '1根', required: false },
      { name: '香醋', amount: '3勺', required: false },
      { name: '白糖', amount: '2勺', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '白芝麻', amount: '1勺', required: false },
    ],
    instructions: [
      '排骨斩小段冷水下锅，加葱段姜片焯水煮沸撇净血沫，捞出温水冲净沥干。',
      '热锅倒少许底油，放入排骨中小火慢煎至表面微焦黄微脆。',
      '加入调好的黄金糖醋汁（料酒1勺、生抽2勺、糖3勺、醋4勺、开水小半碗）。',
      '大火煮沸转中小火盖盖焖烧15-20分钟至排骨酥软入味。',
      '开大火快速翻炒收汁，见汤汁浓稠红亮紧紧包裹在排骨上，出锅撒上白芝麻。',
    ],
    tips: '糖醋汁牢记1酒2酱3糖4醋口诀，最后大火收汁让糖汁焦化包裹，色泽更红润光亮。',
    image_url: '/images/dishes/recipe_sweet_sour_ribs.webp',
  },
  {
    id: 'recipe-corn-ribs-soup',
    name: '玉米山药排骨汤',
    category: '养生汤羹',
    cuisine: '粤菜靓汤',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 45,
    servings: 4,
    ingredients: [
      { name: '排骨', amount: '400g', required: true },
      { name: '玉米', amount: '1根', required: true },
      { name: '山药', amount: '1根', required: true },
      { name: '生姜', amount: '3片', required: false },
      { name: '盐', amount: '适量', required: false },
      { name: '枸杞', amount: '1小把', required: false },
    ],
    instructions: [
      '排骨斩小块焯水洗净；甜玉米切厚段轮圈；山药去皮切滚刀块浸清水防氧化。',
      '砂锅中放入排骨、玉米段和生姜片，一次性加入足量冷水或热水。',
      '大火烧沸后转微火慢炖30分钟至骨香四溢。',
      '加入山药块继续煲煮15分钟至山药软糯甘甜。',
      '关火前5分钟加入洗净的枸杞和适量盐调味即可享用清甜靓汤。',
    ],
    tips: '煮排骨汤中途切忌加冷水，出锅前再放盐能保持肉质鲜嫩汤色清亮。',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
  },
  {
    id: 'recipe-garlic-sprout-pork',
    name: '蒜苔炒肉丝',
    category: '家常菜',
    cuisine: '家常小炒',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 6,
    servings: 2,
    ingredients: [
      { name: '蒜苔', amount: '250g', required: true },
      { name: '猪肉', amount: '150g', required: true },
      { name: '生姜', amount: '2片', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '盐', amount: '半勺', required: false },
      { name: '淀粉', amount: '1勺', required: false },
    ],
    instructions: [
      '猪瘦肉切细丝加生抽、料酒、生粉和少许油抓匀腌制5分钟；蒜苔洗净切成4厘米长小段。',
      '热锅凉油，下肉丝快速划散至变白断生立刻盛出。',
      '锅内留少许底油爆香姜丝，倒入蒜苔大火翻炒至表面微起小皱，撒少许水焖1分钟促其熟软。',
      '倒回肉丝加生抽和少许盐，大火急火快炒30秒翻匀出锅。',
    ],
    tips: '蒜苔先炒至八成熟再倒回肉丝，肉丝嫩滑不柴，蒜苔脆嫩爽口带清甜。',
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500',
  },
  {
    id: 'recipe-hunan-pork-egg',
    name: '农家一碗香',
    category: '家常菜',
    cuisine: '湘菜',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '猪肉', amount: '150g', required: true },
      { name: '鸡蛋', amount: '3个', required: true },
      { name: '青椒', amount: '2根', required: true },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
    ],
    instructions: [
      '热油锅直接打入3个鸡蛋煎成金黄酥脆的荷包蛋，用锅铲切成适口大块盛出。',
      '猪五花肉切薄片，青椒切斜滚刀块，大蒜切片。',
      '锅留底油下五花肉片中小火煸炒出油脂微卷焦黄，放入蒜片和青椒大火炒出辣香。',
      '倒回煎好的荷包蛋块，调入生抽、蚝油和少许白糖。',
      '大火快速翻炒均匀让肉香蛋香与青椒鲜辣充分融合，出锅装盘。',
    ],
    tips: '荷包蛋一定要煎出金黄焦边吸汁才过瘾，五花肉煸透不腻、越嚼越香。',
    image_url: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=500',
  },
  {
    id: 'recipe-bean-pork-belly',
    name: '豆角焖五花肉',
    category: '家常菜',
    cuisine: '北方家常',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 15,
    servings: 3,
    ingredients: [
      { name: '豆角', amount: '300g', required: true },
      { name: '五花肉', amount: '200g', required: true },
      { name: '大蒜', amount: '4瓣', required: false },
      { name: '生姜', amount: '2片', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '老抽', amount: '半勺', required: false },
    ],
    instructions: [
      '豆角择去两端老筋掰成寸段洗净；五花肉切成0.5厘米厚片。',
      '热锅下五花肉中小火煸炒逼出多余油脂，炒至微焦上色，下姜蒜末爆香。',
      '倒入豆角大火不断翻炒，炒至豆角表皮微现虎皮白纹。',
      '调入生抽、老抽上色，加入半碗开水没过大半食材。',
      '盖上锅盖中小火焖煮10-12分钟至豆角软烂熟透入味，大火收浓汤汁出锅。',
    ],
    tips: '豆角必须完全焖熟焖透才安全，五花肉油脂浸润豆角让其格外糯软浓香。',
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500',
  },

  // ==========================================
  // 7. 禽肉类（经典川鲁家常、快手滑炒）
  // ==========================================
  {
    id: 'recipe-kung-pao-chicken',
    name: '宫保鸡丁',
    category: '家常菜',
    cuisine: '川菜',
    difficulty: '中等',
    prep_time: 10,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: '250g', required: true },
      { name: '黄瓜', amount: '半根', required: false },
      { name: '胡萝卜', amount: '半根', required: false },
      { name: '辣椒', amount: '3根', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '香醋', amount: '1.5勺', required: false },
      { name: '白糖', amount: '1勺', required: false },
      { name: '淀粉', amount: '1勺', required: false },
    ],
    instructions: [
      '鸡胸肉切小丁加少许生抽、料酒、水淀粉抓匀上浆腌制10分钟；黄瓜胡萝卜切丁。',
      '调宫保小碗汁：生抽2勺、香醋1.5勺、白糖1勺、少许盐、淀粉加3勺水调匀。',
      '热锅热油下干辣椒段花椒炒出香辣味，倒入鸡丁大火滑散至变白成熟。',
      '倒入胡萝卜丁、黄瓜丁大火翻炒1分钟断生。',
      '沿锅边淋入调好的宫保汁，大火快速颠锅让芡汁均匀包裹鸡丁，出锅装盘。',
    ],
    tips: '火候要快，小碗汁提前调好一气呵成，荔枝酸甜微麻微辣，鸡丁滑嫩爽口。',
    image_url: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=500',
  },
  {
    id: 'recipe-mushroom-chicken',
    name: '香菇滑鸡块',
    category: '家常菜',
    cuisine: '粤菜家常',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 12,
    servings: 3,
    ingredients: [
      { name: '鸡腿', amount: '2只', required: true },
      { name: '香菇', amount: '6朵', required: true },
      { name: '生姜', amount: '3片', required: false },
      { name: '大葱', amount: '1根', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '淀粉', amount: '1勺', required: false },
    ],
    instructions: [
      '鸡腿剁成小块洗净沥干，加生抽、蚝油、料酒、淀粉和姜丝腌制15分钟入味。',
      '鲜香菇洗净去蒂切厚片，大葱切段。',
      '热锅倒少许油爆香葱段姜片，倒入腌好的鸡块大火翻炒至鸡皮微黄收紧。',
      '加入香菇片翻炒出菌菇香味，倒入半碗温水大火煮开。',
      '转中小火盖盖焖烧8分钟至鸡块鲜嫩软熟，开盖大火收至汤汁浓稠挂勺出锅。',
    ],
    tips: '鸡腿肉含油脂更丰富多汁不易柴，香菇吸收了鸡油鲜甜滋润极其下饭。',
    image_url: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500',
  },
  {
    id: 'recipe-huangmen-chicken',
    name: '经典黄焖鸡',
    category: '家常菜',
    cuisine: '鲁菜',
    difficulty: '中等',
    prep_time: 12,
    cook_time: 18,
    servings: 3,
    ingredients: [
      { name: '鸡腿', amount: '2只', required: true },
      { name: '香菇', amount: '5朵', required: true },
      { name: '青椒', amount: '1根', required: false },
      { name: '土豆', amount: '1个', required: false },
      { name: '生姜', amount: '4片', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
    ],
    instructions: [
      '鸡腿剁块焯水冲洗沥干；土豆去皮切滚刀块，香菇切厚块，青椒切片。',
      '锅中少油下姜片爆香，放入鸡块中小火翻炒至表皮微微金黄出油。',
      '调入生抽、老抽、蚝油炒匀上色，倒入开水漫过鸡肉表面。',
      '放入土豆块与香菇，大火煮沸后盖盖转小火焖炖12-15分钟至土豆软糯。',
      '倒入青椒片开大火翻炒收浓汤汁，酱汁浓厚包裹食材即可起锅。',
    ],
    tips: '浓郁酱香焖烧入骨，汤汁浸润软烂土豆与米饭拌食是这道招牌菜的绝妙吃法。',
    image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500',
  },
  {
    id: 'recipe-garlic-chicken-wings',
    name: '香煎蒜香鸡翅',
    category: '家常菜',
    cuisine: '家常风味',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 12,
    servings: 2,
    ingredients: [
      { name: '鸡翅', amount: '8只', required: true },
      { name: '大蒜', amount: '1头', required: true },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '黑胡椒', amount: '适量', required: false },
    ],
    instructions: [
      '鸡翅两面各划两刀便于入味；大蒜整头剁成细碎蒜蓉。',
      '鸡翅中加入大半蒜蓉、生抽、蚝油、黑胡椒粉充分抓匀腌制20分钟。',
      '平底锅刷薄油烧热，摆入鸡翅中小火慢煎4-5分钟至底面金黄酥香。',
      '翻面继续慢煎至两面焦黄全熟，下入剩余的生蒜蓉小火翻炒煸出浓烈蒜香。',
      '蒜蓉金黄焦香紧裹鸡翅，出锅装盘趁热食用。',
    ],
    tips: '分批下蒜蓉：腌制入味、最后加蒜提香，小火慢煎能把鸡皮多余油脂逼出更酥脆。',
    image_url: 'https://images.unsplash.com/photo-1527477321055-436158a2b00d?w=500',
  },
  {
    id: 'recipe-cumin-onion-chicken',
    name: '洋葱孜然炒鸡胸',
    category: '减脂轻食',
    cuisine: '家常小炒',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 6,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: '250g', required: true },
      { name: '洋葱', amount: '1个', required: true },
      { name: '生抽', amount: '2勺', required: false },
      { name: '孜然粉', amount: '2小勺', required: false },
      { name: '辣椒粉', amount: '1小勺', required: false },
      { name: '白芝麻', amount: '1勺', required: false },
    ],
    instructions: [
      '鸡胸肉顺纹切薄片加生抽、料酒、淀粉和少许油抓匀锁水腌制；洋葱切粗丝。',
      '热锅热油下鸡胸肉片快速滑散至变白断生立刻盛出沥油。',
      '锅留底油下洋葱丝大火快速翻炒1分钟，炒至洋葱边缘微变透明散发清甜。',
      '倒回鸡肉片，撒入足量孜然粉、辣椒粉和白芝麻。',
      '大火快速爆炒翻匀，烧烤风味扑鼻即可关火盛盘。',
    ],
    tips: '鸡胸肉切薄片加油和淀粉锁水，口感滑嫩完全不干柴，洋葱提供天然甘甜。',
    image_url: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=500',
  },

  // ==========================================
  // 8. 牛肉与水产海鲜类（鲜味浓郁、营养丰富）
  // ==========================================
  {
    id: 'recipe-scallion-beef',
    name: '葱爆牛肉',
    category: '家常菜',
    cuisine: '京鲁风味',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 5,
    servings: 2,
    ingredients: [
      { name: '牛肉', amount: '250g', required: true },
      { name: '大葱', amount: '2根', required: true },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '淀粉', amount: '1勺', required: false },
    ],
    instructions: [
      '牛肉逆着纹路切薄片，加生抽、蚝油、淀粉和少许食用油抓匀上浆腌制10分钟。',
      '大葱斜切成大滚刀段，蒜切片备用。',
      '热锅多放些油烧至七成热，倒入腌好的牛肉片大火急火滑炒至八成熟变色迅速盛出。',
      '锅留底油爆香蒜片和大葱段，大火爆炒出浓烈葱焦香。',
      '倒回牛肉片，淋少许生抽调味，大火爆炒20秒翻匀立刻关火出锅。',
    ],
    tips: '大葱要分量足并用滚刀段，全程大火爆炒锁住肉汁，牛肉滑嫩大葱焦香。',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500',
  },
  {
    id: 'recipe-pepper-beef-tenderloin',
    name: '杭椒牛柳',
    category: '家常菜',
    cuisine: '江浙菜',
    difficulty: '中等',
    prep_time: 10,
    cook_time: 6,
    servings: 2,
    ingredients: [
      { name: '牛肉', amount: '250g', required: true },
      { name: '青椒', amount: '4根', required: true },
      { name: '生姜', amount: '2片', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '黑胡椒', amount: '1小勺', required: false },
      { name: '淀粉', amount: '1勺', required: false },
    ],
    instructions: [
      '牛里脊顺纹切条逆纹切细长牛柳，加生抽、料酒、蛋清、淀粉抓上劲后淋少许油封住。',
      '杭椒/青椒洗净斜切长段。',
      '热锅温油倒入牛柳快速划散至断生变色，盛出控油。',
      '底油爆香姜丝，下杭椒段煸炒至表皮微微发白起小虎皮。',
      '倒入牛柳撒入现磨黑胡椒碎和生抽，大火颠锅翻炒半分钟出锅。',
    ],
    tips: '牛柳滑油时间切忌过长，刚变色即可出锅，杭椒清爽微辣与黑椒牛香相得益彰。',
    image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500',
  },
  {
    id: 'recipe-steamed-seabass',
    name: '清蒸鲈鱼',
    category: '海鲜水产',
    cuisine: '粤菜',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 8,
    servings: 3,
    ingredients: [
      { name: '鲈鱼', amount: '1条', required: true },
      { name: '大葱', amount: '2根', required: true },
      { name: '生姜', amount: '1块', required: true },
      { name: '生抽', amount: '2勺', required: false },
      { name: '食用油', amount: '2勺', required: false },
    ],
    instructions: [
      '鲈鱼处理干净洗净血水，在鱼身两侧背部各斜划两刀，鱼肚和盘底铺上姜片葱段。',
      '蒸锅加水大火烧沸上汽，放入鱼盘大火蒸7-8分钟，关火虚蒸2分钟。',
      '倒掉盘中蒸出的腥水，拿掉垫底发黄的旧葱姜。',
      '在鱼身表面铺上新鲜切细的葱丝和姜丝，沿盘边淋入蒸鱼豉油或淡盐生抽。',
      '另起小锅烧热2勺食用油至微冒青烟，迅速淋在葱姜丝上激发出浓郁香气。',
    ],
    tips: '大火开水上锅蒸，盘底腥水务必倒掉，滚烫热油泼在葱丝上是鱼肉爽滑鲜甜的秘诀。',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500',
  },
  {
    id: 'recipe-steamed-basa-fish',
    name: '葱油金针菇蒸巴沙鱼',
    category: '海鲜水产',
    cuisine: '快手蒸菜',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '巴沙鱼', amount: '250g', required: true },
      { name: '金针菇', amount: '1把', required: true },
      { name: '小葱', amount: '2根', required: false },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '白胡椒粉', amount: '适量', required: false },
    ],
    instructions: [
      '巴沙鱼柳洗净吸干水分切厚片，加少许料酒、白胡椒粉、少许盐和淀粉抓匀腌制5分钟。',
      '金针菇去根洗净撕开，平铺在深盘底部。',
      '将腌好的巴沙鱼片整齐码在金针菇上，表面撒上蒜末。',
      '蒸锅水烧开后入锅，大火蒸6-8分钟至鱼肉雪白鲜嫩。',
      '出锅撒上葱花，淋上生抽，泼入一勺烧热的热油激出葱香。',
    ],
    tips: '巴沙鱼无骨无刺肉质柔嫩，底部的金针菇充分吸收了鱼肉鲜汤，滑爽入味。',
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500',
  },
  {
    id: 'recipe-braised-prawns',
    name: '秘制油焖大虾',
    category: '海鲜水产',
    cuisine: '鲁菜经典',
    difficulty: '中等',
    prep_time: 8,
    cook_time: 8,
    servings: 2,
    ingredients: [
      { name: '虾', amount: '300g', required: true },
      { name: '生姜', amount: '3片', required: false },
      { name: '大葱', amount: '1段', required: false },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '白糖', amount: '1.5勺', required: false },
      { name: '香醋', amount: '半勺', required: false },
    ],
    instructions: [
      '鲜虾剪掉虾须虾枪开背挑出虾线，清洗沥干水分。',
      '锅中多倒些油烧热，下大虾中小火煎炒，用锅铲轻轻按压虾头挤出红亮虾油。',
      '虾身变红两面酥脆后盛出；锅留红亮虾油爆香葱姜蒜碎。',
      '倒入生抽、白糖、香醋和两勺清水大火烧沸。',
      '倒回大虾翻匀盖锅盖焖煨2分钟让虾肉充分吸收汤汁，大火收浓虾油汁裹紧虾壳出锅。',
    ],
    tips: '按压虾头炒出红虾油是鲜香色泽的关键，虾壳酥脆肉质紧实，咸甜适口。',
    image_url: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=500',
  },
  {
    id: 'recipe-loofah-clam-soup',
    name: '丝瓜蛤蜊鲜汤',
    category: '养生汤羹',
    cuisine: '沿海家常',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 6,
    servings: 2,
    ingredients: [
      { name: '蛤蜊', amount: '300g', required: true },
      { name: '丝瓜', amount: '1根', required: true },
      { name: '生姜', amount: '3片', required: false },
      { name: '盐', amount: '适量', required: false },
      { name: '小葱', amount: '少许', required: false },
    ],
    instructions: [
      '蛤蜊提前泡淡盐水吐沙洗净外壳；丝瓜削去外皮切滚刀块。',
      '热锅倒少许油放入姜片爆香，倒入丝瓜块大火翻炒至微微变软。',
      '加入足量开水大火烧滚2分钟，下入洗净的蛤蜊。',
      '大火煮至蛤蜊张开贝壳，加适量盐调味，出锅撒上葱花即关火装碗。',
    ],
    tips: '蛤蜊开口立刻关火保持肉质饱满柔嫩，丝瓜碧绿甘润，汤汁自带天然鲜甜。',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
  },
  {
    id: 'recipe-clam-steamed-egg',
    name: '蛤蜊蒸蛋',
    category: '家常菜',
    cuisine: '家常蒸菜',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 10,
    servings: 2,
    ingredients: [
      { name: '鸡蛋', amount: '3个', required: true },
      { name: '蛤蜊', amount: '200g', required: true },
      { name: '生姜', amount: '2片', required: false },
      { name: '小葱', amount: '1根', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '香油', amount: '半勺', required: false },
    ],
    instructions: [
      '蛤蜊洗净冷水下锅加姜片煮至微微开口捞出摆在蒸盘中，留原汤澄清晾凉。',
      '鸡蛋加少许盐充分打散，按1:1.5比例加入温凉的蛤蜊原汤搅匀并过筛滤去浮沫。',
      '将蛋液均匀缓缓倒入摆有蛤蜊的蒸盘中，盖上耐高温保鲜膜扎几个小孔。',
      '水开上汽后中小火蒸8-10分钟至蛋羹滑嫩凝固。',
      '出锅揭去保鲜膜，淋少许生抽、香油，撒上细葱花即可享用。',
    ],
    tips: '用煮蛤蜊的原汤调蛋液是鲜味倍增的独家窍门，过筛加盖保鲜膜蒸出的蛋面如镜面般光滑。',
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500',
  },

  // ==========================================
  // 9. 蔬菜与豆制品类（清爽少油、常备素味）
  // ==========================================
  {
    id: 'recipe-fried-green-beans',
    name: '经典干煸四季豆',
    category: '家常菜',
    cuisine: '川菜',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 10,
    servings: 2,
    ingredients: [
      { name: '四季豆', amount: '300g', required: true },
      { name: '猪肉', amount: '60g', required: false },
      { name: '大蒜', amount: '4瓣', required: false },
      { name: '辣椒', amount: '3根', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '盐', amount: '半勺', required: false },
    ],
    instructions: [
      '四季豆洗净择去两侧老筋掰成寸段，厨房纸擦干表面水分。',
      '锅内倒适量油烧热，放入四季豆中小火慢煸至表皮微焦皱起虎皮纹，捞出控油。',
      '锅留底油下肉末、蒜蓉和辣椒段煸炒出香味。',
      '倒回煸好的四季豆大火爆炒，调入生抽和少许盐颠锅翻匀。',
      '水分煸干且豆角完全熟透后关火出锅。',
    ],
    tips: '四季豆务必彻底煸炒熟透，表面微焦起皱干香不油腻，麻辣咸鲜十分开胃。',
    image_url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500',
  },
  {
    id: 'recipe-oyster-sauce-lettuce',
    name: '白灼蚝油生菜',
    category: '家常菜',
    cuisine: '粤菜',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 3,
    servings: 2,
    ingredients: [
      { name: '生菜', amount: '300g', required: true },
      { name: '大蒜', amount: '4瓣', required: true },
      { name: '蚝油', amount: '2勺', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '白糖', amount: '半勺', required: false },
    ],
    instructions: [
      '生菜一片片掰开彻底洗净沥干。',
      '锅中烧沸水加入半小勺盐和几滴食用油，放入生菜烫15-20秒断生立刻捞出沥水装盘。',
      '热锅凉油下蒜末小火慢炒出浓郁蒜香至微微金黄。',
      '加入蚝油、生抽、白糖和两勺清水搅匀煮沸成浓香蚝油酱汁。',
      '将滚烫浓郁的蒜香蚝油汁均匀浇淋在生菜上即可。',
    ],
    tips: '焯水加盐和油能保持生菜翠绿清脆，焯水时间切不可过长以免发软失脆。',
    image_url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500',
  },
  {
    id: 'recipe-garlic-water-spinach',
    name: '蒜蓉空心菜',
    category: '家常菜',
    cuisine: '家常小炒',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 3,
    servings: 2,
    ingredients: [
      { name: '空心菜', amount: '300g', required: true },
      { name: '大蒜', amount: '5瓣', required: true },
      { name: '盐', amount: '半小勺', required: false },
      { name: '鸡精', amount: '少许', required: false },
    ],
    instructions: [
      '空心菜摘洗干净切成长段，沥干水分；大蒜拍碎切成蒜末。',
      '炒锅烧至很热，倒入适量食用油爆香大半蒜末。',
      '大火迅速倒入空心菜，全程猛火快速颠翻翻炒1分半钟至菜叶变软。',
      '出锅前加入盐、少许鸡精和剩余生蒜末快速炒匀，立刻出锅装盘。',
    ],
    tips: '炒空心菜的核心是火大油热速度快，出锅前再放盐，菜叶油绿脆嫩不发黑。',
    image_url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500',
  },
  {
    id: 'recipe-supreme-broth-baby-cabbage',
    name: '上汤娃娃菜',
    category: '家常菜',
    cuisine: '粤菜精选',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 8,
    servings: 3,
    ingredients: [
      { name: '娃娃菜', amount: '2颗', required: true },
      { name: '皮蛋', amount: '1个', required: false },
      { name: '香肠', amount: '半根', required: false },
      { name: '大蒜', amount: '4瓣', required: false },
      { name: '盐', amount: '适量', required: false },
    ],
    instructions: [
      '娃娃菜纵向对切成四瓣洗净；皮蛋、香肠切小粒，大蒜去皮拍松。',
      '热锅倒少许油下蒜瓣小火煎至两面金黄微皱，下皮蛋丁和香肠丁大火翻炒出香味。',
      '倒入一大碗滚水，大火保持沸腾熬煮2-3分钟形成奶白浓厚高汤。',
      '放入娃娃菜中小火炖煮3-4分钟至软烂鲜嫩，加少许盐调味。',
      '将娃娃菜捞出整齐码入汤碗，倒入醇厚浓白的上汤和配料即可。',
    ],
    tips: '大蒜煎黄配皮蛋加沸水大火滚煮，无需浓汤宝就能轻松熬出鲜美奶白的醇香高汤。',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
  },
  {
    id: 'recipe-black-pepper-king-oyster',
    name: '黑椒手撕杏鲍菇',
    category: '素食轻食',
    cuisine: '家常创新',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 6,
    servings: 2,
    ingredients: [
      { name: '杏鲍菇', amount: '2个', required: true },
      { name: '青椒', amount: '1根', required: false },
      { name: '大蒜', amount: '2瓣', required: false },
      { name: '生抽', amount: '1.5勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '黑胡椒', amount: '1小勺', required: false },
    ],
    instructions: [
      '杏鲍菇洗净顺着纤维手撕成细长条；青椒切丝，大蒜切片。',
      '不粘锅不放油下入撕好的杏鲍菇丝，中小火干煸出多余水分至菇丝变软微黄后盛出。',
      '锅内倒少许油爆香蒜片，下青椒丝和煸软的杏鲍菇丝大火翻炒。',
      '加入生抽、蚝油和现磨黑胡椒碎大火快速翻炒均匀入味出锅。',
    ],
    tips: '手撕比刀切更具肌理感且更入味，先干煸逼出水汽让菇丝口感如同肉丝般弹韧干香。',
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500',
  },
  {
    id: 'recipe-mushroom-greens',
    name: '香菇炒青菜',
    category: '家常菜',
    cuisine: '家常素菜',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 5,
    servings: 2,
    ingredients: [
      { name: '青菜', amount: '300g', required: true },
      { name: '香菇', amount: '5朵', required: true },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '盐', amount: '半勺', required: false },
    ],
    instructions: [
      '青菜洗净沥水对半切，鲜香菇洗净切厚片，蒜切末。',
      '锅中烧沸水加少许盐和油，下入青菜焯水30秒捞出沥干在盘中围成一圈。',
      '热锅倒少许油爆香蒜末，倒入香菇片大火翻炒至出水变软散发浓香。',
      '调入生抽、蚝油和少许清水焖煮2分钟至软滑入味，用水淀粉勾薄芡。',
      '将炒好的浓汁香菇盛在青菜盘中心即可。',
    ],
    tips: '青菜脆嫩清香，香菇吸收蚝油滑润浓郁，色泽碧绿油润荤素得宜。',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500',
  },
  {
    id: 'recipe-crispy-home-style-tofu',
    name: '外焦里嫩家常豆腐',
    category: '家常菜',
    cuisine: '家常川味',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 10,
    servings: 2,
    ingredients: [
      { name: '老豆腐', amount: '1块', required: true },
      { name: '青椒', amount: '1根', required: false },
      { name: '木耳', amount: '1小把', required: false },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '蚝油', amount: '1勺', required: false },
      { name: '豆瓣酱', amount: '1勺', required: false },
    ],
    instructions: [
      '老豆腐切厚度约0.8厘米的三角厚片，厨房纸吸干表面多余水分。',
      '平底锅多倒些油烧热，将豆腐片逐块放入中小火慢煎至两面金黄酥脆起硬壳后盛出。',
      '锅留底油爆香蒜末和豆瓣酱炒出红油，下入泡发好的木耳和青椒块大火翻炒。',
      '倒回煎好的外焦豆腐片，加入生抽、蚝油和半碗开水小火焖炖3分钟让豆腐吸汁。',
      '大火收紧浓郁汤汁，使每片豆腐裹满酱香即可出锅。',
    ],
    tips: '煎豆腐切忌频繁翻动，一面金黄定型后再翻面，外壳酥脆内芯多汁蜂窝吸饱酱汁。',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500',
  },
  {
    id: 'recipe-century-egg-tofu',
    name: '皮蛋拌豆腐',
    category: '凉拌菜',
    cuisine: '经典凉菜',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 0,
    servings: 2,
    ingredients: [
      { name: '嫩豆腐', amount: '1盒', required: true },
      { name: '皮蛋', amount: '2个', required: true },
      { name: '大蒜', amount: '3瓣', required: false },
      { name: '小葱', amount: '2根', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '香醋', amount: '1勺', required: false },
      { name: '香油', amount: '1勺', required: false },
    ],
    instructions: [
      '内酯嫩豆腐盒子四角各剪一小口，倒扣在盘中划切成适口小方块。',
      '皮蛋剥壳切小丁，整齐铺在嫩豆腐上方。',
      '大蒜剁成蒜蓉，葱切葱花。',
      '小碗中加入蒜末、生抽、香醋、香油和少许盐糖拌匀调成灵魂凉拌汁。',
      '将调好的酱汁均匀淋在皮蛋豆腐上，撒上葱花，食用时用勺子轻轻拌匀。',
    ],
    tips: '嫩豆腐冰镇后再拌口感更爽滑解暑，香油香醋能极大激发皮蛋独特的醇厚风味。',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
  },

  // ==========================================
  // 10. 经典主食与快手便饭（一锅端、饭面齐备）
  // ==========================================
  {
    id: 'recipe-golden-egg-fried-rice',
    name: '黄金粒粒蛋炒饭',
    category: '经典主食',
    cuisine: '家常主食',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 6,
    servings: 1,
    ingredients: [
      { name: '米饭', amount: '1碗', required: true },
      { name: '鸡蛋', amount: '2个', required: true },
      { name: '小葱', amount: '2根', required: true },
      { name: '盐', amount: '半勺', required: false },
      { name: '白胡椒粉', amount: '少许', required: false },
    ],
    instructions: [
      '剩米饭压散；1个蛋黄拌入米饭抓匀让米粒裹上金黄蛋液；剩余全蛋加蛋白打散。',
      '热锅热油倒入蛋液快速划散凝固成金黄蛋碎盛出备用。',
      '锅留底油爆香葱白，倒入裹满蛋黄的米饭大火翻炒，压炒结合至米粒跳舞粒粒分明。',
      '倒回炒好的蛋碎，撒入少许盐和白胡椒粉大火翻匀。',
      '出锅前撒入翠绿葱花翻炒数秒，香气四溢即可出锅。',
    ],
    tips: '生蛋黄提前裹拌冷饭，大火翻炒水分蒸发米粒自然金黄分开、颗颗分明有嚼劲。',
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500',
  },
  {
    id: 'recipe-scallion-oil-noodles',
    name: '葱油拌面',
    category: '经典主食',
    cuisine: '本帮风味',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 10,
    servings: 1,
    ingredients: [
      { name: '面条', amount: '1把', required: true },
      { name: '小葱', amount: '1把', required: true },
      { name: '生抽', amount: '2勺', required: false },
      { name: '老抽', amount: '1勺', required: false },
      { name: '白糖', amount: '1勺', required: false },
      { name: '食用油', amount: '3勺', required: false },
    ],
    instructions: [
      '小葱洗净擦干水分切长段；锅中倒适量油放入葱段，中小火慢炸10分钟至葱段金黄焦脆酥香。',
      '锅内淋入生抽、老抽和白糖，微火搅拌煮至白糖融化冒细小密集气泡即可关火成葱油汁。',
      '另起大锅烧水，水滚下入面条煮熟，捞出过温水沥干放入面碗。',
      '在面条上淋入两大勺熬好的浓香葱油汁，放上炸得焦脆的葱段，趁热迅速挑拌均匀。',
    ],
    tips: '小火慢熬出葱油焦香，甜咸适中的秘制酱汁包裹劲道面条，简单快手却香入骨髓。',
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500',
  },
  {
    id: 'recipe-tomato-fried-egg-noodles',
    name: '番茄浓汤荷包蛋面',
    category: '经典主食',
    cuisine: '快手主食',
    difficulty: '简单',
    prep_time: 5,
    cook_time: 8,
    servings: 1,
    ingredients: [
      { name: '面条', amount: '1把', required: true },
      { name: '西红柿', amount: '2个', required: true },
      { name: '鸡蛋', amount: '1个', required: true },
      { name: '大蒜', amount: '2瓣', required: false },
      { name: '生抽', amount: '1勺', required: false },
      { name: '盐', amount: '半勺', required: false },
    ],
    instructions: [
      '西红柿切小碎丁，大蒜切碎末备用。',
      '热锅倒油打入鸡蛋，中小火煎成两面焦黄酥脆的荷包蛋盛出。',
      '锅底留油爆香蒜末，倒入番茄碎大火炒出浓厚红汤沙汁，加1勺生抽翻匀。',
      '倒入一大碗开水大火煮沸，放入煎好的荷包蛋和面条中火煮3分钟至面条熟透劲道。',
      '撒入少许盐调味，连汤带面盛入碗中，酸甜开胃暖心暖胃。',
    ],
    tips: '番茄切小碎丁翻炒出红沙是汤底浓郁的秘诀，荷包蛋吸足酸甜汤汁口感极其多汁。',
    image_url: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
  },
  {
    id: 'recipe-cantonese-cured-meat-rice',
    name: '广式腊味煲仔饭',
    category: '经典主食',
    cuisine: '粤菜传统',
    difficulty: '中等',
    prep_time: 15,
    cook_time: 20,
    servings: 2,
    ingredients: [
      { name: '大米', amount: '150g', required: true },
      { name: '香肠', amount: '2根', required: true },
      { name: '鸡蛋', amount: '1个', required: false },
      { name: '青菜', amount: '2棵', required: false },
      { name: '生抽', amount: '2勺', required: false },
      { name: '白糖', amount: '半勺', required: false },
      { name: '香油', amount: '半勺', required: false },
    ],
    instructions: [
      '大米洗净浸泡30分钟，砂锅底刷薄油放入大米加适量水（米水比约1:1.2），大火烧开转小火焖煮至表面现小孔蜂窝状。',
      '广式腊肠切薄斜片铺在米饭上，中间打入一颗生鸡蛋。',
      '盖上锅盖极小火焖煮8-10分钟，沿砂锅盖边缘淋一圈花生油形成金黄焦香锅巴。',
      '关火继续虚焖5分钟；青菜烫熟后摆入砂锅中。',
      '淋入调好的煲仔饭甜酱油（生抽、糖、少许水和香油煮沸），趁热将焦脆锅巴与腊味米饭拌匀。',
    ],
    tips: '沿锅边淋油小火慢焙能结出金黄焦香嘎嘣脆的锅巴，腊肠油脂融入米粒油润香浓。',
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500',
  },
  {
    id: 'recipe-preserved-egg-pork-congee',
    name: '皮蛋瘦肉粥',
    category: '经典主食',
    cuisine: '粤式靓粥',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 25,
    servings: 3,
    ingredients: [
      { name: '大米', amount: '100g', required: true },
      { name: '猪肉', amount: '80g', required: true },
      { name: '皮蛋', amount: '2个', required: true },
      { name: '生姜', amount: '2片', required: false },
      { name: '小葱', amount: '1根', required: false },
      { name: '盐', amount: '1小勺', required: false },
      { name: '白胡椒粉', amount: '少许', required: false },
    ],
    instructions: [
      '大米洗净加少许油和盐抓匀腌制10分钟；锅中加足量水大火烧开下米，大火翻滚15分钟熬至浓稠起胶开米花。',
      '猪瘦肉切细丝加料酒、少许盐和淀粉抓匀腌制；皮蛋去壳切小丁，生姜切极细姜丝。',
      '白粥底粘稠后放入姜丝和一半皮蛋丁继续熬煮5分钟让皮蛋熔入粥底增鲜。',
      '下入腌好的肉丝和剩余皮蛋丁大火滚煮3-4分钟至肉丝嫩白熟透。',
      '关火前调入少许盐、白胡椒粉和香油，撒上细葱花即可享用香浓滑糯靓粥。',
    ],
    tips: '米先加油腌制再开水下锅，米粒开花极快且粥底绵密丝滑，分两次放皮蛋让粥体既有底味又有颗粒嚼劲。',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
  },

  // ==========================================
  // 11. 养生暖胃靓汤（老少皆宜、鲜美润燥）
  // ==========================================
  {
    id: 'recipe-winter-melon-meatball-soup',
    name: '冬瓜肉丸汤',
    category: '养生汤羹',
    cuisine: '家常靓汤',
    difficulty: '简单',
    prep_time: 10,
    cook_time: 10,
    servings: 3,
    ingredients: [
      { name: '冬瓜', amount: '300g', required: true },
      { name: '猪肉', amount: '200g', required: true },
      { name: '生姜', amount: '2片', required: false },
      { name: '小葱', amount: '1根', required: false },
      { name: '盐', amount: '1小勺', required: false },
      { name: '白胡椒粉', amount: '少许', required: false },
    ],
    instructions: [
      '猪瘦肉剁成细腻肉糜，加葱姜水、少许生抽、盐和淀粉顺同一方向快速搅打至起胶上劲。',
      '冬瓜去皮去瓤切薄片备用。',
      '锅内加清水和姜片烧至微沸转微火，用虎口挤出圆润肉丸用小勺刮入锅中定型。',
      '全部肉丸下锅后转中火煮沸撇净浮沫，下入冬瓜片煮5分钟至冬瓜透亮软烂。',
      '调入少许盐、白胡椒粉和香油，撒上细葱花关火出锅。',
    ],
    tips: '微沸定型肉丸不易散开，冬瓜清甜利水吸满肉香，汤清味美肉丸爽脆多汁。',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
  },
  {
    id: 'recipe-mushroom-tofu-fresh-soup',
    name: '菌菇三鲜豆腐汤',
    category: '养生汤羹',
    cuisine: '家常素汤',
    difficulty: '简单',
    prep_time: 8,
    cook_time: 8,
    servings: 3,
    ingredients: [
      { name: '豆腐', amount: '1块', required: true },
      { name: '菌菇', amount: '150g', required: true },
      { name: '鸡蛋', amount: '1个', required: false },
      { name: '小葱', amount: '1根', required: false },
      { name: '盐', amount: '1小勺', required: false },
      { name: '白胡椒粉', amount: '少许', required: false },
    ],
    instructions: [
      '嫩豆腐切小丁；菌菇（金针菇、白玉菇或平菇）洗净撕小朵沥干。',
      '热锅倒少许油打入鸡蛋煎成金黄荷包蛋切条备用（或出锅前打入蛋花）。',
      '锅内留底油倒入菌菇中小火翻炒1-2分钟，炒出菌菇清香和少许汁水。',
      '倒入大碗开水大火烧沸，加入豆腐块和煎蛋中火煮3-5分钟至汤汁奶白鲜香。',
      '加适量盐、少许白胡椒粉调味，淋少许香油撒上葱花出锅。',
    ],
    tips: '菌菇先煸炒再加滚烫开水，菌汤立刻泛起奶白色，无需高汤也能极其鲜醇浓厚。',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500',
  },
];
